# --- compute/variables.tf
variable "name_tag_prefix" {}
variable "aws_resource_owner_name" {}
variable "key_name" {}
variable "public_key_path" {}
variable "tower_version" {}
variable "tower_server_count" {}
variable "tower_instance_type" {}
variable "node_instance_type" {}
variable "tower_sg" {}
variable "inventory_node_sg" {}
variable "public_subnet" {}
variable "private_subnet" {}
variable "tower_root_partition_size" {}
variable "public_nodes_count" {}
variable "private_nodes_count" {}
variable "public_win_nodes_count" {}
variable "inventory_win_node_sg" {}
variable "win_node_instance_type" {}
variable "private_win_nodes_count" {}